apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-operator-kube-p-prometheus
  type: NodePort
  ports:
    - name: http-web
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31090  # Đặt NodePort ở đây, hoặc để Kubernetes tự chọn
    - name: reloader-web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31808  # Đặt NodePort ở đây, hoặc để Kubernetes tự chọn

